# Generated by Django 4.2.7 on 2023-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
