# Generated by Django 5.0 on 2023-12-29 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
        ),
    ]
