# Generated by Django 5.0 on 2023-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_bookings_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
